services:
  web: 
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./www:/www
      - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
      - php
  
  php:
    build:
      context: .
      dockerfile: php-fpm.dockerfile
    container_name: php-fpm
    volumes:
      - ./www:/www
    links:
      - db
  
  db:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    restart: always
    env_file:
      - ./.env
